{ pkgs, ...}: {
  
  wayland.windowManager.hyprland = {
    
    enable = true;
    xwayland.enable = true;
    portalPackage = pkgs.xdg-desktop-portal-hyprland;

    settings = {
      autogenerated = 0;
      "monitor" = ",preferred,auto,1";

      env = [ "XDG_DATA_DIRS,$HOME/.local/share/flatpak/exports/sahre:/var/lib/flatpak/exports/share:$XDG_DATA_DIRS" "HYPRCURSOR_THEME,Bibata-Modern-Ice" "HYPRCURSOR_SIZE,24" ];

      # General
      general = {
        gaps_in = 3;
        gaps_out = 10;
        border_size = 2;

        # Colors
        "col.active_border" = "rgb(d9faf8) rgb(d9faf8) 120deg";
        "col.inactive_border" = "rgb(292e2e) rgb(292e2e) 45deg";

        layout = "master";

      };

      master = {
        new_on_top = true;
        mfact = "0.50";
      };

      # Decorations
      decoration = {
        rounding = 3;
        inactive_opacity = 0.7;
        active_opacity = 1;
        fullscreen_opacity = 1;

        blur = {
          enabled = true;
          size = 7;
          passes = 1;
          new_optimizations = true;
        };
      };
      
      # Animations
      animations = {
        enabled = true;

        bezier = "myBezier, 0.32, 0, 0.67, 0";

        animation = [
          "windowsIn, 1, 2, myBezier, popin 75%"
          "windowsOut, 1, 2, myBezier, popin 75%"
          # layersIn and layersOut inherit layers configs
          "layers, 1, 2, myBezier, popin 70%"
          "fadeIn, 1, 3, myBezier"
          "fadeOut, 1, 3, myBezier"
          "workspacesIn, 1, 2, myBezier, slidefade 30%"
          "workspacesOut, 1, 2, myBezier, slidefade 30%"
          "border, 1, 2, myBezier"
        ];
      };
      
      # Setting up the keybindings
      "$mainMod" = "SUPER";
      "bind" = [
        "$mainMod, U, exec, wezterm"
        "$mainMod, Y, killactive"
        "$mainMod, N, exec, firefox"
        "$mainMod, F, togglefloating"
        "$mainMod, M, exit"
        "$mainMod, space, exec, fuzzel"

        "$mainMod, H, movefocus, l"
        "$mainMod, L, movefocus, r"
        "$mainMod, K, movefocus, u"
        "$mainMod, J, movefocus, d"

        "$mainMod, I, workspace, -1"
        "$mainMod, O, workspace, +1"

        "Alt, I, movetoworkspace, -1"
        "Alt, O, movetoworkspace, +1"

        # Bindings for master layout 
        "$mainMod, P, layoutmsg, swapwithmaster"
        "$mainMod, B, layoutmsg, cyclenext"
        "$mainMod, C, layoutmsg, mfact +0.10"
        "$mainMod, V, layoutmsg, mfact -0.10"

      ];
      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizewindow"
      ];

      exec-once = [
        "hyprpaper"
        "waybar"
        "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP PATH"
        "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP PATH"
      ];
    };
  };
}
