{ pkgs, pkgs-unstable, config, ... }:
{
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;

    settings = {
      autogenerated = 0;
      "monitor" = ",preferred,auto,1";

      general = {
        gaps_in = 5;
        gaps_out = 14;
        border_size = 2;

        "col.active_border" = "rgb(d9faf8) rgb(d9faf8) 150deg";
        "col.inactive_border" = "rgb(292e2e) rgb(292e2e) 150deg";

        layout = "master";

      };
      
      master = {
        new_on_top = true;
        mfact = "0.60";
    };

    decorations = {
      rounding = 2;
      inactive_opacity = 0.6;
      active_opacity = 1;
      fullscreen_opacity = 1;

      blur = {
        enabled = false;
        # size = 7;
        # passes = 1;
        # new_optimizations = true;
      };
    };

    animations = {
      enabled = true;
      bezier = "myBezier, 0.32, 0, 0.67, 0";

      animation = [
        "windowsIn, 1, 2, myBezier, popin 80%"
        "windowsOut, 1, 2, myBezier, popin 80%"
        "layers, 1, 2, myBezier, popin 70%"
        "fadeIn, 1, 5, myBezier"
        "fadeOut, 1, 5, myBezier"
        "workspacesIn, 1, 2, myBezier, slidefade 30%"
        "workspacesOut, 1, 2, myBezier, slidefade 30%"
        "border, 1, 2, myBezier"
      ];
    };

    "$mainMod" = "SUPER";
    "bind" = [
      "$mainMod, U, exec, alacritty"
      "$mainMod, Y, killactive"
      "$mainMod, N, exec, firefox"
      "$mainMod, F, togglefloating"
      "$mainMod, Q, exit"
      "$mainMod, space, exec, fuzzel"

      "$mainMod, H, movefocus, l"
      "$mainMod, L, movefocus, r"
      "$mainMod, K, movefocus, u"
      "$mainMod, J, movefocus, d"

      "$mainMod, I, workspace, -1"
      "$mainMod, O, workspace, +1"

      "Alt, I, movetoworkspace, -1"
      "Alt, O, movetoworkspace, +1"

      "$mainMod, P, layoutmsg, swapwithmaster"
      "$mainMod, M, layoutmsg, cyclenext"
      "$mainMod, V, layoutmsg, mfact -0.05"
      "$mainMod, B, layoutmsg, mfact +0.05"
    ];

    exec-once = [
      "swww img ../../../resources/bubbles.jpg"
      "waybar"
    ];
  };
}
