{ pkgs, pkgs-unstable, config, lib, ... }:
{
  imports = [
    # the autogenerated hardware configuration by nixos
    /etc/nixos/hardware-configuration.nix
    # System-wide packages
    ./config-modules/system_packages.nix
    # Fonts
    ./config-modules/fonts.nix
    # General services
    ./config-modules/system_services.nix
    # General settings
    ./config-modules/system_settings.nix
    # Program settings
    ./config-modules/system_programs.nix
  ];

  system.stateVersion = "25.11";
}
